[package]
name = "progenitor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }

[[bin]]
name = "progenitor"
path = "src/main.rs"

[[bin]]
name = "pgen"
path = "src/main.rs"
